
# YML version
version: '3'

# Define all the services 
services:
  order-service:  # node application
    restart: always # automatically restart if the app fails
    build: ./order-service # build the image from the dockerfile present in the order-service directory
    image: tendawa123/order-service:0.0.1
    depends_on:
      - postgresql
      - rabbitmq
    environment: # environment variables
      - PORT=3000
      - MQ_HOST=rabbitmq
      - MONGO_HOST=mongo # this should be the same as the name of the DB service below
      - SLEEP_TIME=20000
    ports: 
      - '3000:3000' # map the ports as <host-port>:<container-port . The container-port should be the same as the PORT defined in environment.
  
  restaurant-service:  # node application
    restart: always # automatically restart if the app fails
    build: ./restaurant-service # build the image from the dockerfile present in the restaurant-service directorries
    image: tendawa123/restaurant-service:0.0.1
    depends_on:
      - mongo
      - rabbitmq
    environment: # environment variables
      - MQ_HOST=rabbitmq
      - MONGO_HOST=mongo # this should be the same as the name of the DB service below
      - PREFETCH_COUNT=3 # Max orders that can be processed simultaneously
      - SLEEP_TIME=20000
  
  email-service:  # node application
    restart: always # automatically restart if the app fails
    build: ./email-service # build the image from the dockerfile present in the restaurant-service directory
    image: tendawa123/email-service:1.0.0
    depends_on:
      - rabbitmq
    environment: # environment variables
      - MQ_HOST=rabbitmq
      - PREFETCH_COUNT=3 # Max orders that can be processed simultaneously
      - SLEEP_TIME=20000
  
  postgresql: # database
    image: mongo:4.2 # pull the mongo image from docker hub
    logging: 
      driver: none # disable logging
    ports:
      - '27017:27017'
  
  rabbitmq: # rabbitmq
    image: rabbitmq:3.8.9 # pull the rabbitmq image from  dockerhub
    logging: 
      driver: none # disable logging
    ports:
      - '5672:5672'
